apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: reversewords-qa-app
  namespace: reverse-words-qa
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - reversewords-qa-app
