apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: reversewords-qa-app-subscription
  namespace: reverse-words-qa
  labels:
    app: reversewords-qa-app
  annotations:
    apps.open-cluster-management.io/git-path: apps/reversewords/
    apps.open-cluster-management.io/git-branch: qa
spec:
  channel: open-cluster-management/acm-app-lifecycle
  placement:
    placementRef:
      kind: PlacementRule
      name: qa-clusters
